audodo/apps/sleep/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from .views import (
    AddAwakening,
    AddNap,
    CreateOrUpdateCurrentDay,
    CreateOtherDay,
    EditAwakening,
    EditNap,
    EditOtherDay,
    History,
    HistoryCurrentMonth,
    Index,
)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path(
        _("current-day/update/"),
        CreateOrUpdateCurrentDay.as_view(),
        name="update_current_day",
    ),
    path(
        _("other-days/edit/<slug:day>/"), EditOtherDay.as_view(), name="edit_other_day"
    ),
    path(
        _("other-days/add/<slug:day>/"),
        CreateOtherDay.as_view(),
        name="create_other_day",
    ),
    path(
        _("history/"),
        HistoryCurrentMonth.as_view(),
        name="history_current_month",
    ),
    path(
        _("history/<int:year>/<int:month>/"),
        History.as_view(),
        name="history",
    ),
    path(
        _("awakenings/add/<slug:day>/"),
        AddAwakening.as_view(),
        name="add_nocturnal_awakening",
    ),
    path(
        _("awakenings/edit/<slug:day>/<int:pk>/"),
        EditAwakening.as_view(),
        name="edit_nocturnal_awakening",
    ),
    path(
        _("nap/add/<slug:day>/"),
        AddNap.as_view(),
        name="add_nap",
    ),
    path(
        _("nap/edit/<slug:day>/<int:pk>/"),
        EditNap.as_view(),
        name="edit_nap",
    ),
]

app_name = "sleep"

audodo/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path(
        _("account/"), include(("django.contrib.auth.urls", "user"), namespace="user")
    ),
    path("", include("audodo.apps.sleep.urls", namespace="sleep")),
)

audodo/apps/sleep/models.py
from datetime import timedelta

from django.db import models
from django.utils.translation import gettext_lazy as _

from audodo.apps.user.models import User

LEVELS = (
    ("very bad", _("Very bad")),
    ("bad", _("Bad")),
    ("ok", _("Ok")),
    ("good", _("Good")),
    ("very good", _("Very Good")),
)


class SleepLogDay(models.Model):
    user = models.ForeignKey(
        User,
        related_name="sleep_log_entries",
        on_delete=models.CASCADE,
        verbose_name=_("User"),
    )
    day = models.DateField(verbose_name=_("Day"))
    lay_down_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Lay down hour")
    )
    sleep_start_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Sleep start hour")
    )
    sleep_end_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Sleep end hour")
    )
    get_up_hour = models.TimeField(null=True, blank=True, verbose_name=_("Get up hour"))

    quality_of_sleep = models.CharField(
        max_length=32,
        choices=LEVELS,
        null=True,
        blank=True,
        verbose_name=_("Quality of sleep"),
    )
    condition_on_waking = models.CharField(
        max_length=32,
        choices=LEVELS,
        null=True,
        blank=True,
        verbose_name=_("Condition on waking"),
    )
    condition_during_the_day = models.CharField(
        max_length=32,
        choices=LEVELS,
        null=True,
        blank=True,
        verbose_name=_("Condition during the day"),
    )
    comment = models.CharField(
        max_length=1024, null=True, blank=True, verbose_name=_("Comment")
    )

    @property
    def status_emoji(self):
        if self.is_complete:
            return "✅"
        return "🟧"

    @property
    def tomorrow(self):
        return self.day + timedelta(days=1)

    @property
    def is_complete(self):
        return (
            self.sleep_start_hour
            and self.sleep_end_hour
            and self.lay_down_hour
            and self.get_up_hour
            and self.quality_of_sleep
            and self.condition_on_waking
            and self.condition_during_the_day
        )

    @property
    def sleep_start_hour_no_seconds(self):
        if self.sleep_start_hour:
            return self.sleep_start_hour.isoformat(timespec="minutes")
        return None

    @property
    def sleep_end_hour_no_seconds(self):
        if self.sleep_end_hour:
            return self.sleep_end_hour.isoformat(timespec="minutes")
        return None

    @property
    def lay_down_hour_no_seconds(self):
        if self.lay_down_hour:
            return self.lay_down_hour.isoformat(timespec="minutes")
        return None

    @property
    def get_up_hour_no_seconds(self):
        if self.get_up_hour:
            return self.get_up_hour.isoformat(timespec="minutes")
        return None

    @property
    def get_day_str(self):
        return self.day.strftime("%B %d, %Y")

    @property
    def get_tomorrow_str(self):
        return self.tomorrow.strftime("%B %d, %Y")

    @property
    def simple_str(self):
        if self.is_complete:
            return f"from {self.sleep_start_hour_no_seconds} to {self.sleep_end_hour_no_seconds}"
        return _("Incomplete")

    def __str__(self):
        return (
            _("From")
            + " "
            + self.get_day_str
            + " "
            + _("to")
            + " "
            + self.get_tomorrow_str
        )

    class Meta:
        verbose_name = _("Sleep log day")
        verbose_name_plural = _("Sleep log days")


class NocturnalAwakening(models.Model):
    night = models.ForeignKey(
        SleepLogDay,
        on_delete=models.CASCADE,
        related_name="awakenings",
        verbose_name=_("Night"),
    )
    sleep_end_hour = models.TimeField(verbose_name=_("Sleep end hour"))
    get_up_hour = models.TimeField(
        null=True,
        blank=True,
        help_text=_("Only if you got out of bed."),
        verbose_name=_("Get up hour"),
    )
    lay_down_hour = models.TimeField(
        null=True,
        blank=True,
        help_text=_("Only if you got out of bed."),
        verbose_name=_("Lay down hour"),
    )
    sleep_start_hour = models.TimeField(verbose_name=_("Sleep start hour"))
    comment = models.CharField(
        max_length=1024, null=True, blank=True, verbose_name=_("Comment")
    )

    class Meta:
        verbose_name = _("Nocturnal awakening")
        verbose_name_plural = _("Nocturnal awakenings")


class Nap(models.Model):
    user = models.ForeignKey(
        User,
        related_name="nap_entries",
        on_delete=models.CASCADE,
        verbose_name=_("User"),
    )
    day = models.DateField(verbose_name=_("Day"))
    lay_down_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Lay down hour")
    )
    sleep_start_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Sleep start hour")
    )
    sleep_end_hour = models.TimeField(
        null=True, blank=True, verbose_name=_("Sleep end hour")
    )
    get_up_hour = models.TimeField(null=True, blank=True, verbose_name=_("Get up hour"))
    comment = models.CharField(
        max_length=1024, null=True, blank=True, verbose_name=_("Comment")
    )

    class Meta:
        verbose_name = _("Nap")
        verbose_name_plural = _("Naps")

audodo/apps/user/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser

# from django.db import models


class User(AbstractUser):
    pass

audodo/apps/sleep/forms.py
from django import forms

from .models import SleepLogDay


class SleepLogDayForm(forms.ModelForm):
    class Meta:
        model = SleepLogDay
        exclude = ["user", "day"]

audodo/apps/sleep/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    ListView,
    RedirectView,
    TemplateView,
    UpdateView,
    View,
)

from .forms import SleepLogDayForm
from .models import Nap, NocturnalAwakening, SleepLogDay
from .utils import get_all_days_for_month, get_next_month, get_previous_month


class Index(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            current_day = timezone.now().date()
            yesterday = current_day - timedelta(1)
            last_night = SleepLogDay.objects.filter(
                user=self.request.user, day=yesterday
            ).first()
            if last_night and not last_night.is_complete:
                context["last_day"] = last_night
                context["yesterday"] = yesterday
                context["previous_sleep_log_day_form"] = SleepLogDayForm(
                    instance=last_night
                )
            context["sleep_log_day"] = SleepLogDay.objects.filter(
                user=self.request.user, day=current_day
            ).first()
            context["sleep_log_day_form"] = SleepLogDayForm(
                initial={"day": current_day, "user": self.request.user},
                instance=context["sleep_log_day"],
            )
            context["naps"] = Nap.objects.filter(
                user=self.request.user, day=current_day
            )
            context["nocturnal_awakenings"] = NocturnalAwakening.objects.filter(
                night=context["sleep_log_day"]
            )
            context["current_day"] = current_day
            context["tomorrow"] = current_day + timedelta(days=1)
        return context


class CreateOrUpdateCurrentDay(LoginRequiredMixin, View):
    def post(self, request):
        sleep_log_day, created = SleepLogDay.objects.get_or_create(
            user=self.request.user, day=timezone.now()
        )
        form = SleepLogDayForm(request.POST, instance=sleep_log_day)
        if form.is_valid():
            form.save()
            messages.success(request, _("Your current day data have been updated."))
        else:
            messages.error(
                request, _(f"There was an error or more on your form: {form.errors}")
            )
        return redirect(reverse("sleep:index"))


class History(LoginRequiredMixin, ListView):
    template_name = "sleep/history.html"
    model = SleepLogDay
    context_object_name = "nights"

    def get_queryset(self):
        qs = (
            super()
            .get_queryset()
            .filter(
                user=self.request.user,
                day__month=self.kwargs["month"],
                day__year=self.kwargs["year"],
            )
        )
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        current_month = timezone.now().month

        context["time"] = f"{self.kwargs['month']} {self.kwargs['year']}"

        previous_month, previous_year = get_previous_month(
            self.kwargs["month"], self.kwargs["year"]
        )
        context["previous_month"] = {
            "year": previous_year,
            "month": previous_month,
        }

        context["next_month"] = False
        if (self.kwargs["month"], self.kwargs["year"]) != (
            current_month,
            timezone.now().year,
        ):
            next_month, next_year = get_next_month(
                self.kwargs["month"], self.kwargs["year"]
            )
            context["next_month"] = {
                "year": next_year,
                "month": next_month,
            }

        context["all_days"] = get_all_days_for_month(
            self.kwargs["month"], self.kwargs["year"]
        )
        for i in range(len(context["all_days"])):
            context["all_days"][i] = datetime.strptime(
                f"{self.kwargs['year']}-{self.kwargs['month']}-{context['all_days'][i]}",
                "%Y-%m-%d",
            ).date()

        # TODO: fix this ugly function? idk, I want to include all existing days in this list I got, but I don't know how to do it outside the get_context_data function for now
        for night in self.get_queryset():
            context["all_days"][night.day.day - 1] = night

        context["all_days"].reverse()  # we want next day on top of the page

        context["days_to_come"] = []
        context["previous_days"] = context["all_days"]

        if current_month == self.kwargs["month"]:
            remaining_days_til_end_of_month = (
                len(context["all_days"]) - datetime.now().day
            )
            context["days_to_come"] = context["all_days"][
                0:remaining_days_til_end_of_month
            ]
            context["previous_days"] = context["all_days"][
                remaining_days_til_end_of_month:
            ]

        return context


class HistoryCurrentMonth(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        now = timezone.now()
        return reverse(
            "sleep:history",
            kwargs={
                "year": now.year,
                "month": now.month,
            },
        )


class CreateOtherDay(LoginRequiredMixin, CreateView):
    template_name = "sleep/add_other_day.html"
    model = SleepLogDay
    fields = [
        "lay_down_hour",
        "sleep_start_hour",
        "sleep_end_hour",
        "get_up_hour",
        "quality_of_sleep",
        "condition_on_waking",
        "condition_during_the_day",
        "comment",
    ]

    def form_valid(self, form):
        form.instance.day = datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date()
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["day"] = datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date()
        return context

    def get_success_url(self):
        messages.success(
            self.request,
            _(f"The data for day {self.object.day} has been successfully updated."),
        )
        return reverse("sleep:edit_other_day", kwargs={"day": self.object.day})


class EditOtherDay(LoginRequiredMixin, UpdateView):
    template_name = "sleep/other_day.html"
    model = SleepLogDay
    fields = [
        "lay_down_hour",
        "sleep_start_hour",
        "sleep_end_hour",
        "get_up_hour",
        "quality_of_sleep",
        "condition_on_waking",
        "condition_during_the_day",
        "comment",
    ]

    def get_object(self, *args, **kwargs):
        sleep_log_day, created = SleepLogDay.objects.get_or_create(
            user=self.request.user,
            day=datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date(),
        )
        return sleep_log_day

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_day = datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date()
        context["sleep_log_day"] = SleepLogDay.objects.filter(
            user=self.request.user, day=current_day
        ).first()
        context["naps"] = Nap.objects.filter(user=self.request.user, day=current_day)
        context["nocturnal_awakenings"] = NocturnalAwakening.objects.filter(
            night=context["sleep_log_day"]
        )
        context["current_day"] = current_day
        context["tomorrow"] = current_day + timedelta(days=1)
        return context

    def get_success_url(self):
        messages.success(
            self.request,
            _(f"The data for day {self.object.day} has been successfully updated."),
        )
        return reverse("sleep:edit_other_day", kwargs={"day": self.object.day})


class AddAwakening(LoginRequiredMixin, CreateView):
    model = NocturnalAwakening
    template_name = "sleep/add_awakening.html"
    fields = [
        "sleep_end_hour",
        "get_up_hour",
        "lay_down_hour",
        "sleep_start_hour",
        "comment",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["date"] = self.kwargs["day"]
        return context

    def form_valid(self, form):
        day = datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date()
        night = SleepLogDay.objects.get(user=self.request.user, day=day)
        form.instance.night = night
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(
            self.request,
            _(f"Successfully added an awakening for day {self.object.night.day}."),
        )
        if (
            datetime.strptime(self.kwargs["day"], "%Y-%m-%d").date()
            != timezone.now().date
        ):
            return reverse("sleep:edit_other_day", kwargs={"day": self.kwargs["day"]})
        return reverse("sleep:index")


class EditAwakening(LoginRequiredMixin, UpdateView):
    model = NocturnalAwakening
    template_name = "sleep/edit_awakening.html"
    fields = [
        "sleep_end_hour",
        "get_up_hour",
        "lay_down_hour",
        "sleep_start_hour",
        "comment",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["date"] = self.kwargs["day"]
        return context

    def get_success_url(self):
        messages.success(
            self.request,
            _(f"Edited awakening for day {self.object.night.day}."),
        )
        return reverse(
            "sleep:nocturnal_awakening_list", kwargs={"day": self.kwargs["day"]}
        )


class AddNap(LoginRequiredMixin, CreateView):

audodo/apps/user/views.py
from django.shortcuts import render

# Create your views here.

audodo/templates/base.html
{% load i18n static audodo_tags %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <title>
      {% block title %}
        {% if user.is_authenticated %}{% translate "Home" %}{% else %}{% translate "Dashboard" %}{% endif %}
      {% endblock title %} | audodo
    </title>
    <link rel="preload" as="style" href="{% static "css/simple.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/simple.min.css" %}" />
    <link rel="preload" as="style" href="{% static "css/design.css" %}" />
    <link rel="stylesheet" href="{% static "css/design.css" %}" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/png" href="{% static "images/favicon.png" %}" />
  </head>
  <body>
    <header>
      {% block h1 %}
        <h1>audodo</h1>
      {% endblock h1 %}
      <nav>
        {% block nav %}
          <ul>
            <li><a href="{% url "sleep:index" %}">{% translate "Home" %}</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url "sleep:history_current_month" %}">{% translate "History" %}</a></li>
              <li><a href="{% url "user:logout" %}">{% translate "Logout" %}</a></li>
            {% else %}
              <li><a href="{% url "user:login" %}">{% translate "Login" %}</a></li>
            {% endif %}
          </ul>
        {% endblock nav %}
      </nav>
    </header>
    <main>
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }} notice"{% endif %}>{{ message|safe }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% block main %}
        {% if user.is_authenticated %}

          {% if last_day %}
            <section>
              <h2>{% translate "Last night" %}</h2>
              {% blocktranslate %}
                <p>
                  Night before {{ yesterday }} and {{ current_day }}.<br />
                </p>
                <p class="helptext">
                  This is the data for the last night. It is shown here because it's missing some data. Once complete, it will disappear from your homepage.
                </p>
              {% endblocktranslate %}
              <details>
                <summary>{% translate "Show/hide the form" %}</summary>
                <form method="post" action="{% url "sleep:edit_other_day" yesterday %}">
                  {% csrf_token %}
                  {{ previous_sleep_log_day_form.as_p }}
                  <input type="submit" value="{% translate "Update" %}" />
                </form>
                </details
              </section>
          {% endif %}

          <section>
            <h2>{% translate "This night" %}</h2>
            <p>
              {% blocktranslate %}Night before {{ current_day }} and {{ tomorrow }}.{% endblocktranslate %}
            </p>
            <form method="post" action="{% url "sleep:update_current_day" %}">
              {% csrf_token %}
              {{ sleep_log_day_form.as_p }}
              <input type="submit" value="{% translate "Update" %}" />
            </form>
          </section>

          {% include "sleep/naps_and_awakenings_list.html" %}

        {% else %}
          {% include "hello_world.html" %}
        {% endif %}

      {% endblock main %}
    </main>
    <footer>
      {% block footer %}
        {% translate "audodo" %} {% get_version %} &mdash; <a href="https://gitlab.com/sodimel/audodo">{% translate "Check the code" %}</a> &mdash;
        <form action="{% url 'set_language' %}" method="post" style="display: inline-block;">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}">
          <select name="language">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.code }}
              </option>
            {% endfor %}
          </select>
          <input type="submit" value="{% translate 'Apply' %}">
        </form>
      {% endblock footer %}
    </footer>
  </body>
</html>

audodo/templates/hello_world.html
{% load static i18n %}

<img src="{% static "images/logo.png" %}" alt="{% translate "Audodo logo" %}" />

<p>
  {% translate "Welcome to audodo!"%}
</p>

<p>
  {% translate "Audodo is a free and open source sleep diary, where you can save your sleep data :" %}
</p>

<ul>
  <li>{% translate "Lay down hour" %}</li>
  <li>{% translate "Sleep start hour" %}</li>
  <li>{% translate "Sleep end hour" %}</li>
  <li>{% translate "Get up hour" %}</li>
  <li>{% translate "Quality of sleep" %}</li>
  <li>{% translate "Condition on waking" %}</li>
  <li>{% translate "Condition during the day" %}</li>
  <li>{% translate "Comments" %}</li>
</ul>

<p>
  {% translate "Audodo even lets you save your naps and nocturnal awakenings."%}
</p>

<p>
  {% translate "The goal behind this tool is to let you discover the optimal sleep duration you need."%}
</p>

<p>
  {% translate "You can see statistics about your sleep schedule, and even export data to pdf files!" %}
</p>

<hr />

{% if can_register %}
  <p>
    <a class="button" href="">
      {% translate "Register now" %}
    </a>
  </p>
{% else %}
  <p>
    <i>{% translate "This instance of audodo does not accept new members, go check another audodo instance, or <a href='https://gitlab.com/sodimel/audodo'>deploy your own</a>." %}</i>
  </p>
{% endif %}